services:
  stats-server:
    build: statistics/stat-service
    image: ewn-stat-service
    container_name: ewn_stat_service
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1

  ewm-service:
    build: main-service
    image: ewn-main-service
    container_name: ewn_main_service
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:16.1
